# @name prompts
GET http://localhost:3333/prompts

###
# @name videos
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
#@nama create transcription
POST http://localhost:3333/videos/4206fc54-7c21-434a-afff-82d81eb6907b/transcription
Content-Type: application/json
Authorization: Bearer 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

{
  "prompt": "rest"
}

###
#@nama generate ai completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "...",
  "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''",
  "temperatura": 0.5
}